### ISSUE TITLE
Version convention

### ISSUE THREAD

**Issue by serejahh** [BoltsFramework/Bolts-Swift#15]
Hi
I'm wondering why don't you bump version after merge into dev? When can I get a "build" with latest changes?

**Comment by nlutsenko** [comment]
Hey @serejahh, that's a really good question!
The way our release cycles currently work is something close to this:
- Merge to `master`
- Do a release cut when any of these conditions are met:
  - Critical bug fix
  - New awesome big feature
  - ~4 weeks passed from last release
  - A lot of changes / small fixes are pending to be released

This said, we are most likely to release a new version (current master) this week.

I am open to proposals and ideas if we want to do nightly/weekly releases though so you can get the latest and greatest at all times.

**Comment by serejahh** [comment]
Thanks for your detailed answer! 
But what are the benefits of this approach compared to `develop` branch and `master` for exactly releases? Company policy? 😃

**Comment by nlutsenko** [comment]
Our approach is to have `master` always reflect the latest state of the code and as close to the production ready quality as possible (sometimes it slips, but we are working hard to make it stable).
This approach eliminates potential confusion for people contributing to it (which branch to pick) as well as  gives you an ability to reference `master` for production if you want the latest things.
