### ISSUE TITLE
Use of undeclared type 'Task'

### ISSUE THREAD

**Issue by oliverfoggin** [BoltsFramework/Bolts-Swift#21]
I have used Bolts with Objective-C before but when I installed this (through Cocoapods) I can't seem to use them.

I'm trying to create a Task of my own but when I use the code from the README...

```
func doSomethingAsync() -> Task<PFObject> {
}
```

I just get the error "Use of undeclared type 'Task'"

I don't think the README is correct as `PFObject` is not found in the entire project.

I can't seem to find an import that works.

Am I doing something wrong?

**Comment by nlutsenko** [comment]
Hey @oliverfoggin, lets figure this out together!
- I assume you added `import BoltsSwift` or `@import BoltsSwift` to the source file you are trying to use this from.
- If there would be a chance you could publish a project that can reproduce an issue, or maybe a source file + pod file that you are trying to use BoltsSwift from - that would be also very helpful.

The `PFObject` example is something we used as a good example of the asynchronous API, that is currently being used and available in Parse ObjC SDK. I would gladly accept/review the PR that changes all of these to use Cocoa / Cocoa Touch set of frameworks and can showcase the API functionality.

**Comment by oliverfoggin** [comment]
Hi Nikita,

I couldn't find an import statement that was accepted and I had no auto completions for anything with Bolts or Swift in it. I'm away from my computer now but will try that as soon as I'm back.

I'll provide a project too if I can't get it working.

Thanks

Oliver

**Comment by nlutsenko** [comment]
Perfect! Thanks for looking into this!

**Comment by nlutsenko** [comment]
And you are right, it could be quite troublesome to find the proper import statement.
Am going to send a README patch that fixes it, so it's straightforward.

**Comment by oliverfoggin** [comment]
Ah, excellent!

I had tried literally everything but `BoltsSwift` as an import.

With that it now all works.

Thanks for the help
