### ISSUE TITLE
error: A cryptographic verification failure has occurred.

### ISSUE THREAD

**Issue by dylankbuckley** [BoltsFramework/Bolts-Swift#31]
Updated mac to developer preview of Sierra and now project wont build instead giving the error on the bolts package saying: error: A cryptographic verification failure has occurred.

**Comment by nlutsenko** [comment]
Hey @dkbuckley, super strange!
I bet this has something to do with macOS Sierra preview and not Bolts.
Any chance you can paste the full error log?

**Comment by nlutsenko** [comment]
Closing per inactivity. Please reopen or comment if this is still an issue.
