### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by PranayDMI** [BoltsFramework/Bolts-Swift#33]
This is not working with the XCode 8.0 & Swift 3.0. Its not compiling with Swift 3.0.

**Comment by nlutsenko** [comment]
We don't yet support Swift 3.0, but we are planning to add it the moment Swift 3.0 goes GM.
As for right now - I would recommend either using a Migration Assistant to migrate to Swift 3.0.

**Comment by nlutsenko** [comment]
This said, we have Swift 2.3 support, which adds support for Xcode 8 on current master (thanks to #27) and release with it is coming soon.

**Comment by nlutsenko** [comment]
@AUgene, @PranayDMI, just released BoltsSwift 1.2.0, which has support for Xcode 8 and Swift 2.3.
I suggest you guys give it a spin and comment here if it still fails for you (in that case, would love to know your setup, since it works great via Carthage and subproject on a test project).

**Comment by mobitronics** [comment]
It's pretty weird, that was the compilation issue due to the wrong syntax. I used the XCode 8.0 default migration tool. 
Now its working fine with XCode 8.0 & Swift 3.0.
Thanks @nlutsenko.

**Comment by simonnarang** [comment]
I was having a similar issue

**Comment by simonnarang** [comment]
When I try to import via Carthage when I run `carthage update` i get the following errors:
```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```
The framework also doesn't show up in Carthage/Build/iOS so I cannot import

**Comment by simonnarang** [comment]
I'm using Xcode 8.0 with swift 3.0 and trying to import via carthage

```
/Carthage/Build/iOS/BoltsSwift.framework/BoltsSwift compiled with older version of Swift 
language (2.0) than previous files (3.0) for architecture x86_64 clang: error: linker 
command failed with exit code 1 (use -v to see invocation)
```

Anyone seen this error before?

**Comment by nlutsenko** [comment]
@simonnarang, I would recommend trying to migrate the framework to Swift 3.0 in your own custom fork using built-in migration assistant from Xcode.

**Comment by simonnarang** [comment]
Okay thanks

**Comment by nlutsenko** [comment]
Hey folks,

Since we have an Xcode beta 4 from this morning - I've just went ahead and migrated the entirety of our sources to current latest Swift 3.0 that comes in the beta.

It lives in [this branch](https://github.com/BoltsFramework/Bolts-Swift/tree/nlutsenko.swift.30). If you are curious or want to use to use the alpha version of Bolts-Swift in Swift 3.0 - I would recommend checking it out.

Please comment here if you run into any issues.
Our stake on supporting Swift 3.0 remains the same - the moment Swift 3.0 goes GM together with Xcode 8.0 - we'll migrate to it and will cut a release.

**Comment by fedetrim** [comment]
@nlutsenko last week, Xcode 8 GM was released. Is there any update on this issue?

**Comment by clayellis** [comment]
Xcode 8 has been released, is anyone actively working on the update? @nlutsenko

**Comment by nlutsenko** [comment]
Hey guys, frankly, am a quite tangled in other things this week, but am going to try my best to get to this by end of this week. Stay tuned for news and look for incoming PRs.
