### ISSUE TITLE
Chaining tasks of different types

### ISSUE THREAD

**Issue by ir-fuel** [BoltsFramework/Bolts-Swift#46]
I have tried all kinds of combinations, but it seems impossible to me to chain several tasks (in series) where the tasks have different result types and whereby each task upon error needs to stop the execution of all subsequent tasks. It's compile time error galore for me.

I also think the docs are lacking. They don't really show how to chain multiple tasks using the success/error handlers. The paragraph `chaining tasks` doesn't even show how to acutally chain tasks.

**Comment by schartyom** [comment]
Can you provide some examples? This compiles for me:
```
func test() -> Task<Void> {
    let stringTask = Task("123")
    let intTask = Task(123)
    let voidTask = Task<Void>.emptyTask()    
    return stringTask.continueOnSuccessWithTask { task in
        return intTask.continueOnSuccessWithTask { task in
            return voidTask
        }
    }
}
```

**Comment by ir-fuel** [comment]
Good point. I tried it again and now I have it working. No idea what happened previously

**Comment by jkmathew** [comment]
the `emptyTask` is internal scope. How can I use it, if I use `Bolts` as framework(using cocoapods/carthage)
