### ISSUE TITLE
Error in the examples for continueOnSuccessWith?

### ISSUE THREAD

**Issue by ir-fuel** [BoltsFramework/Bolts-Swift#51]
According to the readme, `continueOnSuccessWith` is used like this:

```
save(object).continueOnSuccessWith { task in 
  // The object was saved succesfully
  let result = task.result
}
```

however, when trying to use it it actually takes the task result as parameter to the closure, and not the task itself.

code in `Task+ContinueWith.swift`

```
    public func continueOnSuccessWith<S>(_ executor: Executor = .default,
                                      continuation: @escaping ((TResult) throws -> S)) -> Task<S> {

```

And in my own code I have this:

```
runDataTask(request).continueOnSuccessWith { result in
```

**Comment by nlutsenko** [comment]
Hey @ir-fuel, you are quite right, sorry about that.
Let me address this shortly...

I also am keen on redoing some of the examples to provide a slightly more streamlined view on this, together with maybe a Swift Playground, so you can explore using the library right there.
