### ISSUE TITLE
Swift 4 update

### ISSUE THREAD

**Issue by vitaliikuzmenko** [BoltsFramework/Bolts-Swift#61]
Hi, @nlutsenko. Are you planning to deploy an update for swift4? Have some troubles and getting a swift compile error.

**Comment by akwilliamson** [comment]
Has this project been abandoned? It sure seems like it

**Comment by nlutsenko** [comment]
Abandoned - no. 
Me not having spare cycles to update it for Swift 4 - yes.
Bare with me folks, it's coming... Also, if anyone wants to take a stab at it - I'll gladly review the PR.

**Comment by akwilliamson** [comment]
I'm new to contributing but I'm gonna try to give it a go to help upgrade to Swift 4. I think it's just a couple minor updates. I'm trying to run iOS tests but I'm getting errors for these files not found:

> The file “Debug.xcconfig” couldn’t be opened because there is no such file. (/Users/me/OpenSource/Bolts-Swift/Configurations/Shared/Project/Debug.xcconfig)

> BoltsSwiftTests-iOS.xcconfig line 9: Unable to find included file "Shared/Platform/iOS.xcconfig"

> BoltsSwiftTests-iOS.xcconfig line 10: Unable to find included file "Shared/Product/LogicTests.xcconfig"

I assume because after cloning the project, the `Configurations/Shared` symbolic link directory and contents aren't found. How do I link to these? Thanks!

**Comment by akwilliamson** [comment]
I submitted a PR with Swift 4.0 updates

**Comment by akwilliamson** [comment]
@nlutsenko

**Comment by randomiser** [comment]
Any chance we can get the cocoapod updated so we can use this change?

**Comment by addisonElliott** [comment]
I second @randomiser 's answer. 

For those that cannot wait, you can use this in your pod file and it will work:

    pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift.git'

**Comment by randomiser** [comment]
For those looking for an awesome alternative I'd recommend:

https://github.com/khanlou/Promise

Tiny codebase, extremely well architected, and includes support for retries, race, delay, timeouts, etc.

**Comment by addisonElliott** [comment]
@randomiser Will take a look at it! Is there an Android port?

It seems the accepted method of asynchronous on Android and iOS is Rx. The goal someday is to hopefully port Parse libraries over to this on these two platforms

**Comment by randomiser** [comment]
@addisonElliott Not that I know of.
