### ISSUE TITLE
Bumping the podspec version

### ISSUE THREAD

**Issue by akwilliamson** [BoltsFramework/Bolts-Swift#66]
The last podspec version bump was 1.3.0 of last year for Swift 3.0 support. It should be bumped up with changelog for the recent Swift 4.0 changes.

**Comment by tfonfara** [comment]
+1

**Comment by dimaosa** [comment]
+1

**Comment by brianyyz** [comment]
+1

**Comment by randomiser** [comment]
+1

**Comment by ir-fuel** [comment]
+1

**Comment by dmead28** [comment]
+1

**Comment by kevinlee85** [comment]
+1

**Comment by sjmerel** [comment]
+1

**Comment by jkmathew** [comment]
Why this is still open. Is this project not maintained or it is deprecated?

**Comment by ir-fuel** [comment]
The last commit on this project was the 1st of October. My guess is @nlutsenko has other priorities at Facebook right now, so we're stuck.

**Comment by jkmathew** [comment]
@ir-fuel actually we couldn't say we are stuck.
we can use latest version of the repo in our project by specifying git url in Podfile.
Like,
```
pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift.git'
```

**Comment by ir-fuel** [comment]
True, but if there is nobody around to do even this, who is going to fix bugs or merge bug fixes in the main branch for instance.

**Comment by drewster99** [comment]
We really should just dump this library altogether -- it's clear nobody's updating it.

**Comment by ir-fuel** [comment]
Clearly. I've seen some Promise inspired libraries. Guess I'll have to switch too. Too bad.
