### ISSUE TITLE
pod install fetches incorrect files...

### ISSUE THREAD

**Issue by ghost** [BoltsFramework/Bolts-Swift#72]
Hello,

I added pod 'Bolts-Swift' to my podfile and build my app.  I notice the issues were fixed as per: https://github.com/BoltsFramework/Bolts-Swift/pull/64 issue # 64 and if I compare the file on my disk to the one here they are different.  When I run pod install it tells me it is Installing Bolts-Swift (1.3.0)

Can someone tell me what I could be doing wrong?

**Comment by addisonElliott** [comment]
You're not missing anything. The latest version of Bolts released is 1.3.0 which is about a year old. Basically, there are a lot of commits in the repository but they haven't been published to a new version yet.

You can use this in your podfile to get the latest changes from the repository:

    pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift.git'
