### ISSUE TITLE
Swift 5.0 Support

### ISSUE THREAD

**Issue by koushikkarmakar** [BoltsFramework/Bolts-Swift#81]
Will Bolts-Swift be supporting Swift 5.0 anytime soon ?

**Comment by kallanou** [comment]
Up :) There is a pull request...

**Comment by koushikkarmakar** [comment]
@kallanou yeah .. but the current build is failing for some reason. 

I also tried checking out the code and building a Swift 5 Version for my use but for some reason, it doesn't compile with the latest version of Xcode in Mojave ...

**Comment by rostopira** [comment]
Yeah, there are few empty brackets that must be removed

**Comment by frangulyan** [comment]
Any news on this? The PR is so small, should not take half a year to pull.
