### ISSUE TITLE
.xcconfig files for all targets are not found after opening the workspace

### ISSUE THREAD

**Issue by heizo-schulze** [BoltsFramework/Bolts-Swift#89]
e.g.
(userPathShortened)…"/BoltsSwift-iOS.xcconfig BoltsSwift-iOS.xcconfig line 9: Unable to find included file "Shared/Platform/iOS.xcconfig"
Is this my fault? I haven't touched anything, just opened it.

**Comment by nlutsenko** [comment]
Looks like you are missing a submodule checkout.
To fix it - after cloning the repo - run `git submodule update --init --recursive` and you should be good to go.
Let me know if this didn't fix your problem.
