### ISSUE TITLE
Deprecated API Usage: UIWebView

### ISSUE THREAD

**Issue by HackShitUp** [BoltsFramework/Bolts-Swift#96]
Whenever I submit a new build, Apple sends me the following email: 

"ITMS-XXXXX: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information."

It looks like Bolts uses the UIWebView to parse HTML. I'm not sure if this is even a smart thing to do, especially given the fact that December is coming up soon.

**Comment by ljs19923** [comment]
I have the same error... and i cant send my new app to Apple.
@HackShitUp did you find a solution ?

**Comment by HackShitUp** [comment]
@JulienLevallois I was using a library called ParseUI that was using an older version of BoltsSwift. Removing it from my dependencies fixed this.
